version: "3.9"

services:
  db:
    image: postgres:13.7
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moreton
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  backend:
    build: ./backend/
    command: bash start.sh
    volumes:
        - ./backend/:/myapp/
    ports:
        - 8000:8000
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@mbt.com
      DJANGO_SUPERUSER_PASSWORD: password
    depends_on:
      - db
  frontend:
    build: ./frontend/
    command: sh start.sh
    ports:
        - 3000:3000
    depends_on:
      - backend