# Generated by Django 4.0.5 on 2022-07-02 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_app', '0002_remove_role_users_role_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='users',
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
