# Generated by Django 4.0.5 on 2022-07-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_extendeduser_alter_role_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='users',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='roles',
            field=models.ManyToManyField(related_name='roles', to='dashboard_app.role'),
        ),
    ]
