# Generated by Django 4.0.5 on 2022-07-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_remove_role_users_extendeduser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
